package com.jws.app.operater.model;

import java.util.Date;

public class IndusReport {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_report.id
     *
     * @mbggenerated Mon Jul 27 09:48:40 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_report.source_id
     *
     * @mbggenerated Mon Jul 27 09:48:40 CST 2015
     */
    private Integer sourceId;
    
    private String  sourceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_report.title
     *
     * @mbggenerated Mon Jul 27 09:48:40 CST 2015
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_report.url
     *
     * @mbggenerated Mon Jul 27 09:48:40 CST 2015
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_report.abstract_txt
     *
     * @mbggenerated Mon Jul 27 09:48:40 CST 2015
     */
    private String abstractTxt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_report.created_time
     *
     * @mbggenerated Mon Jul 27 09:48:40 CST 2015
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_report.update_time
     *
     * @mbggenerated Mon Jul 27 09:48:40 CST 2015
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_report.remark
     *
     * @mbggenerated Mon Jul 27 09:48:40 CST 2015
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_report.id
     *
     * @return the value of tb_report.id
     *
     * @mbggenerated Mon Jul 27 09:48:40 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_report.id
     *
     * @param id the value for tb_report.id
     *
     * @mbggenerated Mon Jul 27 09:48:40 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_report.source_id
     *
     * @return the value of tb_report.source_id
     *
     * @mbggenerated Mon Jul 27 09:48:40 CST 2015
     */
    public Integer getSourceId() {
        return sourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_report.source_id
     *
     * @param sourceId the value for tb_report.source_id
     *
     * @mbggenerated Mon Jul 27 09:48:40 CST 2015
     */
    public void setSourceId(Integer sourceId) {
        this.sourceId = sourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_report.title
     *
     * @return the value of tb_report.title
     *
     * @mbggenerated Mon Jul 27 09:48:40 CST 2015
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_report.title
     *
     * @param title the value for tb_report.title
     *
     * @mbggenerated Mon Jul 27 09:48:40 CST 2015
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_report.url
     *
     * @return the value of tb_report.url
     *
     * @mbggenerated Mon Jul 27 09:48:40 CST 2015
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_report.url
     *
     * @param url the value for tb_report.url
     *
     * @mbggenerated Mon Jul 27 09:48:40 CST 2015
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_report.abstract_txt
     *
     * @return the value of tb_report.abstract_txt
     *
     * @mbggenerated Mon Jul 27 09:48:40 CST 2015
     */
    public String getAbstractTxt() {
        return abstractTxt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_report.abstract_txt
     *
     * @param abstractTxt the value for tb_report.abstract_txt
     *
     * @mbggenerated Mon Jul 27 09:48:40 CST 2015
     */
    public void setAbstractTxt(String abstractTxt) {
        this.abstractTxt = abstractTxt == null ? null : abstractTxt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_report.created_time
     *
     * @return the value of tb_report.created_time
     *
     * @mbggenerated Mon Jul 27 09:48:40 CST 2015
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_report.created_time
     *
     * @param createdTime the value for tb_report.created_time
     *
     * @mbggenerated Mon Jul 27 09:48:40 CST 2015
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_report.update_time
     *
     * @return the value of tb_report.update_time
     *
     * @mbggenerated Mon Jul 27 09:48:40 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_report.update_time
     *
     * @param updateTime the value for tb_report.update_time
     *
     * @mbggenerated Mon Jul 27 09:48:40 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_report.remark
     *
     * @return the value of tb_report.remark
     *
     * @mbggenerated Mon Jul 27 09:48:40 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_report.remark
     *
     * @param remark the value for tb_report.remark
     *
     * @mbggenerated Mon Jul 27 09:48:40 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

	public String getSourceName() {
		return sourceName;
	}

	public void setSourceName(String sourceName) {
		this.sourceName = sourceName;
	}
}