package com.jws.app.operater.data;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.jws.app.operater.model.IndusReport;
import com.jws.common.data.IMapper;

public interface IndusReportMapper extends IMapper<IndusReport>{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_report
     *
     * @mbggenerated Mon Jul 27 09:48:40 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_report
     *
     * @mbggenerated Mon Jul 27 09:48:40 CST 2015
     */
    int insert(IndusReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_report
     *
     * @mbggenerated Mon Jul 27 09:48:40 CST 2015
     */
    int insertSelective(IndusReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_report
     *
     * @mbggenerated Mon Jul 27 09:48:40 CST 2015
     */
    IndusReport selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_report
     *
     * @mbggenerated Mon Jul 27 09:48:40 CST 2015
     */
    int updateByPrimaryKeySelective(IndusReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_report
     *
     * @mbggenerated Mon Jul 27 09:48:40 CST 2015
     */
    int updateByPrimaryKey(IndusReport record);
    
    /**
     * 获取其他报告
     * @param reportID
     * @return
     */
    public List<IndusReport> selectOtherByKey(@Param("reportID")int reportID);
    
    public List<IndusReport> selectByKeys(@Param("sourceid") int sourceid,@Param("keys") String keys,@Param("pageFrom") int pageFrom,@Param("pageNum") int pageNum) throws Exception;

    public List<IndusReport> selectMoreByKeys(@Param("sourceid") int sourceid,@Param("keys") String keys,@Param("pageFrom") int pageFrom,@Param("pageNum") int pageNum,@Param("lastTime") Date lastTime) throws Exception;
    
    public List<IndusReport> selectAllByKeys(@Param("sourceStrings") String[] sourceStrings,@Param("keys") String keys,@Param("pageFrom") int pageFrom,@Param("pageNum") int pageNum,@Param("lastTime") Date lastTime) throws Exception;
    
    public int selectCountByKeys(@Param("sourceStrings") String[] sourceStrings,@Param("keys") String keys,@Param("lastTime") Date lastTime) throws Exception;

    public int selectNewCountByKeys(@Param("sourceID") int sourceID,@Param("keys") String keys,@Param("lastTime") Date lastTime) throws Exception;
    
    Date selectCurrTime();
}